import gradio as gr
import json
import os
from dotenv import load_dotenv, find_dotenv
from src.config_loader.config_loader import config_loader
from src.modeling.filter_llms import get_available_models
from src.utils.schema import LLMSchema


# load API keys from .env file
load_dotenv(find_dotenv(), override=True)
api_key = os.getenv("OPENROUTER_API_KEY")

# load configuration file
config = config_loader(config_path="config/config.json")

# Get the list of available LLMs
try:
    with open(config.open_router_config.open_router_llms, "r", encoding="utf-8") as open_router_llms:
        open_router_models = json.load(open_router_llms)
except FileNotFoundError:
    raise FileNotFoundError(f"Could not find the LLM list file: {config.open_router_config.open_router_llms}")

available_models = get_available_models(url=config.open_router_config.base_url, 
                                        api_key=api_key,
                                        model_ids=open_router_models)

available_models_names = [llm[LLMSchema.MODEL_NAME] for llm in available_models]
view = gr.Interface(
    inputs=[
        gr.Textbox(label="Compnay Name:"),
        gr.Textbox(label="URL page:"),
        gr.Dropdown([available_models_names], label="Available LLMs:")
    ],
    outputs=gr.Textbox(label="Brochure"),
    title="LLM Brochure Generator",
    description="This application generates a brochure for a company using the specified URL and LLM. The brochure is generated by calling an OpenRouter API endpoint with the provided LLM ID."
)